version: "3"

services:
  postgres:
    restart: unless-stopped
    image: postgres:9.6.20
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "postgres_datadir:/var/lib/postgresql/data"

volumes:
  postgres_datadir:
